// apps/newweb/pages/team-intro/coaches.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

useHead({
  title: '全體教練｜練健康 LKK Wellness',
  meta: [
    {
      name: 'description',
      content: '練健康專業教練團隊，由物理治療師與運動科學專家組成，專注於中高齡健康訓練。'
    }
  ]
})

interface Coach {
  id: string
  name: string
  slug?: string
  photo?: string
  roleTitle?: string
  specialties?: string[]
  certifications?: string[]
  education?: string[]
  experiences?: string[]
  description?: string
  storeId?: string
  store?: {
    id: string
    name: string
    slug: string
  }
}

interface Store {
  id: string
  name: string
  slug: string
}

// Active store filter
const activeStore = ref<string | null>(null)

// Fetch coaches from API
const { data: coachesResponse, pending } = await useFetch<{
  success: boolean
  data: Coach[]
}>('/api/public/coaches')

// Fetch stores for filter navigation
const { data: storesResponse } = await useFetch<{
  success: boolean
  data: Store[]
}>('/api/public/stores')

const coaches = computed(() => coachesResponse.value?.data || [])
const stores = computed(() => storesResponse.value?.data || [])

// Group coaches by store
const coachesByStore = computed(() => {
  const grouped: Record<string, { store: Store | null; coaches: Coach[] }> = {}

  // Initialize with store order
  for (const store of stores.value) {
    grouped[store.slug] = { store, coaches: [] }
  }

  // Add "no store" group for coaches without a store
  grouped['_no_store'] = { store: null, coaches: [] }

  // Group coaches
  for (const coach of coaches.value) {
    const storeSlug = coach.store?.slug
    if (storeSlug && grouped[storeSlug]) {
      grouped[storeSlug].coaches.push(coach)
    } else {
      grouped['_no_store'].coaches.push(coach)
    }
  }

  // Remove empty groups and _no_store if empty
  const result: { store: Store | null; coaches: Coach[] }[] = []
  for (const store of stores.value) {
    if (grouped[store.slug].coaches.length > 0) {
      result.push(grouped[store.slug])
    }
  }
  if (grouped['_no_store'].coaches.length > 0) {
    result.push(grouped['_no_store'])
  }

  return result
})

// Filtered coaches based on active store
const filteredCoachesByStore = computed(() => {
  if (!activeStore.value) {
    return coachesByStore.value
  }
  return coachesByStore.value.filter(g => g.store?.slug === activeStore.value)
})

// Total coach count
const totalCoachCount = computed(() => coaches.value.length)

// Set active store filter
function setActiveStore(storeSlug: string | null) {
  activeStore.value = storeSlug
}

// Scroll to store section
function scrollToStore(storeSlug: string) {
  const element = document.getElementById(`store-${storeSlug}`)
  if (element) {
    const offset = 140 // Account for sticky header + filter bar
    const y = element.getBoundingClientRect().top + window.scrollY - offset
    window.scrollTo({ top: y, behavior: 'smooth' })
  }
}
</script>

<template>
  <div class="min-h-screen bg-cream">
    <!-- Hero Section -->
    <section class="relative bg-navy pt-16 overflow-hidden">
      <div class="absolute inset-0">
        <div class="absolute inset-0 bg-[radial-gradient(circle_at_80%_30%,rgba(251,114,10,0.10)_0%,transparent_55%),radial-gradient(circle_at_5%_75%,rgba(58,106,133,0.3)_0%,transparent_45%)]" />
        <div
          class="absolute inset-0 opacity-[0.022]"
          :style="{
            backgroundImage: 'linear-gradient(rgba(255,255,255,1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,1) 1px, transparent 1px)',
            backgroundSize: '55px 55px',
          }"
        />
      </div>

      <div class="container mx-auto px-4 relative z-10 py-16 lg:py-24 text-center">
        <nav class="flex items-center justify-center gap-1.5 text-xs text-white/35 mb-6">
          <NuxtLink to="/" class="hover:text-white/70 transition-colors">練健康</NuxtLink>
          <span class="text-white/20">›</span>
          <NuxtLink to="/team-intro" class="hover:text-white/70 transition-colors">團隊介紹</NuxtLink>
          <span class="text-white/20">›</span>
          <span>全體教練</span>
        </nav>

        <div class="inline-flex items-center bg-orange/20 border border-orange/40 text-orange text-sm font-medium px-4 py-1.5 rounded-full mb-5">
          物理治療背景專業教練
        </div>

        <h1 class="font-serif text-4xl lg:text-5xl font-black text-white leading-tight mb-4">
          全體<span class="text-orange">教練</span>
        </h1>

        <p class="text-white/60 text-lg font-light leading-relaxed max-w-2xl mx-auto mb-6">
          每位教練都有物理治療師或醫療專業背景，專精於中高齡與特殊族群訓練，讓您在安全的環境下達到最佳訓練效果。
        </p>

        <div class="text-white/40 text-sm">
          共 <span class="text-orange font-semibold">{{ totalCoachCount }}</span> 位專業教練
        </div>
      </div>
    </section>

    <!-- Store Filter Bar -->
    <section class="border-b border-cream-200 sticky top-16 bg-cream/95 backdrop-blur-sm z-20">
      <div class="container mx-auto px-4">
        <div class="flex gap-2 py-4 overflow-x-auto scrollbar-hide">
          <button
            @click="setActiveStore(null)"
            :class="[
              'px-4 py-2 rounded-full whitespace-nowrap font-medium transition-colors',
              activeStore === null
                ? 'bg-navy text-white'
                : 'bg-cream-200 text-ink hover:bg-cream-300'
            ]"
          >
            全部門店
          </button>
          <button
            v-for="store in stores"
            :key="store.slug"
            @click="setActiveStore(store.slug)"
            :class="[
              'px-4 py-2 rounded-full whitespace-nowrap font-medium transition-colors',
              activeStore === store.slug
                ? 'bg-navy text-white'
                : 'bg-cream-200 text-ink hover:bg-cream-300'
            ]"
          >
            {{ store.name }}
          </button>
        </div>
      </div>
    </section>

    <!-- Quick Jump (only visible when showing all) -->
    <section v-if="!activeStore && coachesByStore.length > 1" class="bg-cream-100 border-b border-cream-200">
      <div class="container mx-auto px-4 py-3">
        <div class="flex items-center gap-4 text-sm">
          <span class="text-ink/50">快速跳轉：</span>
          <div class="flex gap-2 flex-wrap">
            <button
              v-for="group in coachesByStore"
              :key="group.store?.slug || 'no-store'"
              @click="scrollToStore(group.store?.slug || 'no-store')"
              class="text-navy hover:text-orange transition-colors"
            >
              {{ group.store?.name || '其他' }} ({{ group.coaches.length }})
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- Loading -->
    <div v-if="pending" class="flex items-center justify-center py-24">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-orange"></div>
    </div>

    <!-- Coaches by Store -->
    <section v-else class="py-12 lg:py-16">
      <div class="container mx-auto px-4">
        <div v-if="filteredCoachesByStore.length === 0" class="text-center py-12 text-ink/50">
          目前沒有教練資料
        </div>

        <div v-else class="space-y-16">
          <!-- Store Section -->
          <div
            v-for="group in filteredCoachesByStore"
            :key="group.store?.slug || 'no-store'"
            :id="`store-${group.store?.slug || 'no-store'}`"
            class="scroll-mt-40"
          >
            <!-- Store Header -->
            <div class="flex items-center gap-4 mb-8">
              <div class="flex-1">
                <div class="flex items-center gap-3 mb-2">
                  <h2 class="font-serif text-2xl lg:text-3xl font-bold text-navy">
                    {{ group.store?.name || '其他門店' }}
                  </h2>
                  <span class="px-3 py-1 bg-orange/10 text-orange text-sm font-medium rounded-full">
                    {{ group.coaches.length }} 位教練
                  </span>
                </div>
                <NuxtLink
                  v-if="group.store"
                  :to="`/locations/${group.store.slug}`"
                  class="text-sm text-ink/50 hover:text-orange transition-colors inline-flex items-center gap-1"
                >
                  查看門店資訊
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                  </svg>
                </NuxtLink>
              </div>
            </div>

            <!-- Coaches Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              <div
                v-for="coach in group.coaches"
                :key="coach.id"
                class="group bg-white rounded-2xl overflow-hidden shadow-sm border border-navy/10 hover:shadow-lg hover:border-orange/30 transition-all duration-300"
              >
                <!-- Coach Image -->
                <div class="aspect-square relative bg-cream-200 overflow-hidden">
                  <img
                    v-if="coach.photo"
                    :src="coach.photo"
                    :alt="coach.name"
                    class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div v-else class="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-navy to-navy/80">
                    <span class="font-serif text-6xl font-black text-white/20">{{ coach.name.charAt(0) }}</span>
                  </div>
                </div>

                <!-- Coach Info -->
                <div class="p-5">
                  <div class="mb-3">
                    <h3 class="text-xl font-bold text-navy font-serif group-hover:text-orange transition-colors">
                      {{ coach.name }}
                    </h3>
                    <p v-if="coach.roleTitle" class="text-orange font-semibold text-sm">
                      {{ coach.roleTitle }}
                    </p>
                  </div>

                  <!-- Specialties -->
                  <div v-if="coach.specialties && coach.specialties.length > 0" class="flex flex-wrap gap-1.5 mb-4">
                    <span
                      v-for="specialty in coach.specialties.slice(0, 3)"
                      :key="specialty"
                      class="px-2.5 py-1 bg-cream text-ink/70 text-xs rounded-full"
                    >
                      {{ specialty }}
                    </span>
                    <span
                      v-if="coach.specialties.length > 3"
                      class="px-2.5 py-1 text-ink/40 text-xs"
                    >
                      +{{ coach.specialties.length - 3 }}
                    </span>
                  </div>

                  <!-- Certifications Preview -->
                  <div v-if="coach.certifications && coach.certifications.length > 0" class="pt-3 border-t border-cream-200">
                    <p class="text-[10px] text-ink/40 uppercase tracking-wider mb-1.5">專業認證</p>
                    <p class="text-xs text-ink/60 line-clamp-2">
                      {{ coach.certifications.slice(0, 2).join('、') }}
                      <span v-if="coach.certifications.length > 2" class="text-ink/40">
                        等 {{ coach.certifications.length }} 項
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA Section -->
    <section class="bg-orange py-16 lg:py-20 text-center">
      <div class="container mx-auto px-4">
        <h2 class="font-serif text-3xl lg:text-4xl font-black text-white mb-3">
          找到適合您的教練了嗎？
        </h2>
        <p class="text-white/80 mb-8 max-w-md mx-auto">
          預約免費體驗，讓專業教練為您評估並制定訓練計畫。50歲以上首次體驗完全免費。
        </p>
        <NuxtLink
          to="/booking"
          class="inline-flex items-center gap-2 bg-white text-orange font-bold px-8 py-3.5 rounded-full shadow-lg hover:-translate-y-0.5 transition-transform"
        >
          立即預約體驗 →
        </NuxtLink>
        <div class="mt-4 text-white/60 text-sm">
          50歲以上完全免費・不強迫買課
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.scrollbar-hide {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
.scrollbar-hide::-webkit-scrollbar {
  display: none;
}
</style>

// apps/web/app/[locale]/team-intro/coaches/page.tsx
import Link from 'next/link';
import { db, CoachDoc, StoreDoc, docsToArray } from '@/lib/firebase';
import { fallbackCoaches, Coach } from '@/lib/fallback-coaches';

// Force dynamic rendering for Firestore data
export const dynamic = 'force-dynamic';

export const metadata = {
  title: '全體教練｜練健康 LKK Wellness',
  description: '練健康專業教練團隊，由物理治療師與運動科學專家組成，專注於中高齡健康訓練。',
};

// 門店名稱對照
const storeNames: Record<string, string> = {
  xindian: '新店七張店',
  nanjing: '南京店',
  songjiang: '松江店',
  ximending: '西門店',
};

// 從 fallback 資料取得所有教練
function getFallbackCoaches() {
  const allCoaches: any[] = [];
  Object.entries(fallbackCoaches).forEach(([storeSlug, coaches]) => {
    coaches.forEach((coach) => {
      allCoaches.push({
        id: coach.id,
        name: coach.name,
        slug: coach.id,
        title: coach.roleTitle || '',
        store: storeNames[storeSlug] || '',
        storeSlug: storeSlug,
        specialties: coach.specialties || [],
        certifications: coach.certifications || [],
        description: '',
        photo: coach.photo,
      });
    });
  });
  return allCoaches;
}

// 從 Firestore 取得教練資料
async function getCoaches() {
  try {
    // 取得所有門店的 Map（用於對照 storeId）
    const storesSnapshot = await db
      .collection('stores')
      .where('isActive', '==', true)
      .get();

    // 如果 Firestore 沒有門店資料，使用 fallback
    if (storesSnapshot.empty) {
      console.log('No stores in Firestore, using fallback coaches data');
      return getFallbackCoaches();
    }

    const storesMap = new Map<string, { name: string; slug: string }>();
    storesSnapshot.docs.forEach((doc) => {
      const data = doc.data();
      storesMap.set(doc.id, { name: data.name, slug: data.slug });
    });

    // 取得所有活躍教練
    const coachesSnapshot = await db
      .collection('coaches')
      .where('isActive', '==', true)
      .orderBy('sortOrder', 'asc')
      .get();

    const coaches = docsToArray<CoachDoc>(coachesSnapshot);

    // 如果 Firestore 沒有教練資料，使用 fallback
    if (coaches.length === 0) {
      console.log('No coaches in Firestore, using fallback coaches data');
      return getFallbackCoaches();
    }

    return coaches.map((coach) => {
      const store = coach.storeId ? storesMap.get(coach.storeId) : null;
      return {
        id: coach.id,
        name: coach.name,
        slug: coach.slug,
        title: coach.roleTitle || '',
        store: store?.name || '',
        storeSlug: store?.slug || '',
        specialties: coach.specialties || [],
        certifications: coach.certifications || [],
        description: coach.description || '',
        photo: coach.photo,
      };
    });
  } catch (error) {
    console.error('Failed to fetch coaches from Firestore, using fallback:', error);
    return getFallbackCoaches();
  }
}

// 從 Firestore 取得門店列表
async function getStores() {
  try {
    const storesSnapshot = await db
      .collection('stores')
      .where('isActive', '==', true)
      .orderBy('sortOrder', 'asc')
      .get();
    const stores = docsToArray<StoreDoc>(storesSnapshot);

    // 如果 Firestore 沒有資料，使用 fallback
    if (stores.length === 0) {
      return [
        { name: '新店七張店', slug: 'xindian' },
        { name: '南京店', slug: 'nanjing' },
        { name: '松江店', slug: 'songjiang' },
        { name: '西門店', slug: 'ximending' },
      ];
    }

    return stores.map((s) => ({ name: s.name, slug: s.slug }));
  } catch (error) {
    console.error('Failed to fetch stores:', error);
    // 使用 fallback
    return [
      { name: '新店七張店', slug: 'xindian' },
      { name: '南京店', slug: 'nanjing' },
      { name: '松江店', slug: 'songjiang' },
      { name: '西門店', slug: 'ximending' },
    ];
  }
}

// Hero Section
function HeroSection() {
  return (
    <section className="relative bg-navy-700 pt-16 overflow-hidden">
      <div className="absolute inset-0">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_30%,rgba(251,114,10,0.10)_0%,transparent_55%),radial-gradient(circle_at_5%_75%,rgba(58,106,133,0.3)_0%,transparent_45%)]" />
        <div
          className="absolute inset-0 opacity-[0.022]"
          style={{
            backgroundImage: 'linear-gradient(rgba(255,255,255,1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,1) 1px, transparent 1px)',
            backgroundSize: '55px 55px',
          }}
        />
      </div>

      <div className="container mx-auto px-4 relative z-10 py-16 lg:py-24 text-center">
        <nav className="flex items-center justify-center gap-1.5 text-xs text-white/35 mb-6">
          <Link href="/" className="hover:text-white/70 transition-colors">練健康</Link>
          <span className="text-white/20">›</span>
          <Link href="/team-intro" className="hover:text-white/70 transition-colors">團隊介紹</Link>
          <span className="text-white/20">›</span>
          <span>全體教練</span>
        </nav>

        <div className="inline-flex items-center bg-orange/20 border border-orange/40 text-orange text-sm font-medium px-4 py-1.5 rounded-full mb-5">
          物理治療背景專業教練
        </div>

        <h1 className="font-serif text-4xl lg:text-5xl font-black text-white leading-tight mb-4">
          全體<span className="text-orange">教練</span>
        </h1>

        <p className="text-white/60 text-lg font-light leading-relaxed max-w-2xl mx-auto">
          每位教練都有物理治療師或醫療專業背景，專精於中高齡與特殊族群訓練，讓您在安全的環境下達到最佳訓練效果。
        </p>
      </div>
    </section>
  );
}

// Store Filter
function StoreFilter({ stores }: { stores: { name: string; slug: string }[] }) {
  return (
    <section className="border-b border-cream-200 sticky top-16 bg-cream-100 z-10">
      <div className="container mx-auto px-4">
        <div className="flex gap-2 py-4 overflow-x-auto">
          <Link
            href="/team-intro/coaches"
            className="px-4 py-2 rounded-full whitespace-nowrap bg-orange text-white"
          >
            全部
          </Link>
          {stores.map((store) => (
            <Link
              key={store.slug}
              href={`/locations/${store.slug}`}
              className="px-4 py-2 rounded-full whitespace-nowrap bg-cream-200 text-ink-600 hover:bg-cream-300 transition-colors"
            >
              {store.name}
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}

// Coach Card
function CoachCard({ coach }: { coach: any }) {
  return (
    <div className="bg-white rounded-2xl overflow-hidden shadow-sm border border-navy-700/10">
      {/* Coach Image */}
      <div className="aspect-square relative bg-cream-200">
        {coach.photo ? (
          <img
            src={coach.photo}
            alt={coach.name}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-navy-700 to-navy-700/80">
            <span className="font-serif text-6xl font-black text-white/20">{coach.name.charAt(0)}</span>
          </div>
        )}
        {/* Store badge */}
        {coach.store && (
          <div className="absolute top-4 right-4 bg-white/90 backdrop-blur-sm text-xs font-medium text-navy-700 px-3 py-1 rounded-full">
            {coach.store}
          </div>
        )}
      </div>

      {/* Coach Info */}
      <div className="p-6">
        <div className="mb-3">
          <h2 className="text-xl font-bold text-navy-700 font-serif">{coach.name}</h2>
          <p className="text-orange font-semibold">{coach.title}</p>
        </div>

        <p className="text-ink/60 text-sm mb-4 line-clamp-2">{coach.description}</p>

        {/* Specialties */}
        {coach.specialties.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-4">
            {coach.specialties.slice(0, 3).map((specialty: string) => (
              <span
                key={specialty}
                className="px-3 py-1 bg-orange/10 text-orange text-xs rounded-full"
              >
                {specialty}
              </span>
            ))}
          </div>
        )}

        {/* Certifications */}
        {coach.certifications.length > 0 && (
          <div className="pt-4 border-t border-cream-200">
            <p className="text-xs text-ink/40 mb-2">專業認證</p>
            <div className="flex flex-wrap gap-1">
              {coach.certifications.slice(0, 2).map((cert: string) => (
                <span key={cert} className="text-xs text-ink/60">
                  {cert}
                </span>
              ))}
              {coach.certifications.length > 2 && (
                <span className="text-xs text-ink/40">+{coach.certifications.length - 2}</span>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Coaches Grid
function CoachesGrid({ coaches }: { coaches: any[] }) {
  if (coaches.length === 0) {
    return (
      <section className="py-16">
        <div className="container mx-auto px-4 text-center">
          <p className="text-ink/60">目前暫無教練資料</p>
        </div>
      </section>
    );
  }

  return (
    <section className="py-12 lg:py-16">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {coaches.map((coach) => (
            <CoachCard key={coach.id} coach={coach} />
          ))}
        </div>
      </div>
    </section>
  );
}

// CTA Section
function CTASection() {
  return (
    <section className="bg-orange py-16 lg:py-20 text-center">
      <div className="container mx-auto px-4">
        <h2 className="font-serif text-3xl lg:text-4xl font-black text-white mb-3">
          找到適合您的教練了嗎？
        </h2>
        <p className="text-white/80 mb-8 max-w-md mx-auto">
          預約免費體驗，讓專業教練為您評估並制定訓練計畫。50歲以上首次體驗完全免費。
        </p>
        <Link
          href="/booking"
          className="inline-flex items-center gap-2 bg-white text-orange font-bold px-8 py-3.5 rounded-full shadow-lg hover:-translate-y-0.5 transition-transform"
        >
          立即預約體驗 →
        </Link>
        <div className="mt-4 text-white/60 text-sm">
          50歲以上完全免費・不強迫買課
        </div>
      </div>
    </section>
  );
}

export default async function AllTrainersPage() {
  const [coaches, stores] = await Promise.all([getCoaches(), getStores()]);

  return (
    <div className="min-h-screen bg-cream-100">
      <HeroSection />
      <StoreFilter stores={stores} />
      <CoachesGrid coaches={coaches} />
      <CTASection />
    </div>
  );
}
