// apps/web/app/admin/(dashboard)/stores/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

interface Store {
  id: string;
  slug: string;
  name: string;
  city: string;
  district: string;
  phone: string;
  isActive: boolean;
}

export default function StoresPage() {
  const [stores, setStores] = useState<Store[]>([]);
  const [loading, setLoading] = useState(true);

  // 從 API 取得門店資料
  useEffect(() => {
    async function fetchStores() {
      try {
        const res = await fetch('/api/admin/stores');
        if (res.ok) {
          const data = await res.json();
          setStores(
            data.data.map((store: any) => ({
              id: store.id,
              slug: store.slug,
              name: store.name,
              city: store.city,
              district: store.district,
              phone: store.phone || '-',
              isActive: store.isActive,
            }))
          );
        }
      } catch (error) {
        console.error('Failed to fetch stores:', error);
      } finally {
        setLoading(false);
      }
    }
    fetchStores();
  }, []);

  const handleToggleActive = async (storeId: string, currentStatus: boolean) => {
    try {
      const res = await fetch(`/api/admin/stores/${storeId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !currentStatus }),
      });
      if (res.ok) {
        setStores((prev) =>
          prev.map((s) => (s.id === storeId ? { ...s, isActive: !currentStatus } : s))
        );
      }
    } catch (error) {
      console.error('Toggle failed:', error);
    }
  };

  const handleDelete = async (storeId: string) => {
    if (confirm('確定要刪除此門店嗎？此操作無法復原。')) {
      try {
        const res = await fetch(`/api/admin/stores/${storeId}`, { method: 'DELETE' });
        if (res.ok) {
          setStores((prev) => prev.filter((s) => s.id !== storeId));
        } else {
          const data = await res.json();
          alert(data.error || '刪除失敗');
        }
      } catch (error) {
        console.error('Delete failed:', error);
      }
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-500">載入中...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold font-sans">門店管理</h1>
          <p className="text-gray-500 mt-1">管理所有門店資訊</p>
        </div>
        <Link href="/admin/stores/new" className="btn btn-primary flex items-center gap-2">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
          新增門店
        </Link>
      </div>

      {/* Table */}
      <div className="card border border-gray-200">
        <div className="table-container">
          <table className="table">
            <thead>
              <tr>
                <th>門店名稱</th>
                <th>地區</th>
                <th>電話</th>
                <th>狀態</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {stores.length === 0 ? (
                <tr>
                  <td colSpan={5} className="text-center py-8 text-gray-500">
                    目前沒有門店資料
                  </td>
                </tr>
              ) : (
                stores.map((store) => (
                  <tr key={store.id}>
                    <td className="font-medium">{store.name}</td>
                    <td>
                      {store.city} {store.district}
                    </td>
                    <td>{store.phone}</td>
                    <td>
                      <button
                        onClick={() => handleToggleActive(store.id, store.isActive)}
                        className={`badge cursor-pointer ${store.isActive ? 'badge-success' : 'badge-gray'}`}
                      >
                        {store.isActive ? '上架中' : '已下架'}
                      </button>
                    </td>
                    <td>
                      <div className="flex items-center gap-2">
                        <Link
                          href={`/admin/stores/${store.id}`}
                          className="text-navy-700 hover:text-navy-800 text-sm"
                        >
                          編輯
                        </Link>
                        <button
                          onClick={() => handleDelete(store.id)}
                          className="text-red-500 hover:text-red-600 text-sm"
                        >
                          刪除
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// apps/newweb/pages/admin/stores.vue
<script setup lang="ts">
definePageMeta({
  layout: 'admin'
})

useHead({
  title: '門店管理｜練健康後台',
})

interface Store {
  id: string
  name: string
  slug: string
  city?: string
  district?: string
  address?: string
  phone?: string
  isActive: boolean
  coachCount?: number
}

const stores = ref<Store[]>([])
const isLoading = ref(true)
const error = ref('')
const showAddModal = ref(false)

// Fetch stores from API
async function fetchStores() {
  isLoading.value = true
  error.value = ''
  try {
    const response = await $fetch<{ success: boolean; data: Store[] }>('/api/admin/stores')
    if (response.success) {
      stores.value = response.data
    }
  } catch (e: any) {
    error.value = e.data?.message || '載入失敗'
    console.error('Error fetching stores:', e)
  } finally {
    isLoading.value = false
  }
}

// Toggle store active status
async function toggleActive(store: Store) {
  try {
    await $fetch(`/api/admin/stores/${store.id}`, {
      method: 'PATCH',
      body: { isActive: !store.isActive },
    })
    store.isActive = !store.isActive
  } catch (e: any) {
    alert(e.data?.message || '更新失敗')
  }
}

// Delete store
async function deleteStore(store: Store) {
  if (!confirm(`確定要刪除「${store.name}」嗎？`)) return
  try {
    await $fetch(`/api/admin/stores/${store.id}`, {
      method: 'DELETE',
    })
    stores.value = stores.value.filter(s => s.id !== store.id)
  } catch (e: any) {
    alert(e.data?.message || '刪除失敗')
  }
}

onMounted(fetchStores)
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">門店管理</h1>
        <p class="text-gray-500 mt-1">管理所有門店資訊與設定</p>
      </div>
      <button
        @click="showAddModal = true"
        class="inline-flex items-center gap-2 bg-orange text-white font-medium px-4 py-2.5 rounded-lg hover:bg-orange-600 transition-colors"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
        新增門店
      </button>
    </div>

    <!-- Error -->
    <div v-if="error" class="bg-red-50 text-red-600 px-4 py-3 rounded-lg mb-4">
      {{ error }}
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="flex items-center justify-center h-64">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-orange"></div>
    </div>

    <!-- Stores Grid -->
    <div v-else class="grid gap-6">
      <!-- Empty State -->
      <div v-if="stores.length === 0" class="bg-white rounded-xl border border-gray-200 shadow-sm p-12 text-center text-gray-500">
        尚無門店資料
      </div>
      <div
        v-for="store in stores"
        :key="store.id"
        class="bg-white rounded-xl border border-gray-200 shadow-sm p-6"
      >
        <div class="flex items-start justify-between">
          <div>
            <div class="flex items-center gap-3 mb-2">
              <h3 class="text-lg font-bold text-gray-900">{{ store.name }}</h3>
              <button
                @click="toggleActive(store)"
                :class="[
                  'text-xs font-medium px-2 py-1 rounded-full cursor-pointer hover:opacity-80 transition-opacity',
                  store.isActive ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'
                ]"
              >
                {{ store.isActive ? '營業中' : '已停用' }}
              </button>
            </div>
            <p class="text-gray-500 text-sm mb-1">{{ store.city }}{{ store.district }}{{ store.address }}</p>
            <p class="text-gray-500 text-sm">{{ store.phone || '-' }}</p>
            <p v-if="store.coachCount !== undefined" class="text-gray-400 text-xs mt-1">{{ store.coachCount }} 位教練</p>
          </div>

          <div class="flex items-center gap-2">
            <NuxtLink
              :to="`/admin/stores/${store.id}`"
              class="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
              title="編輯"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
            </NuxtLink>
            <button
              @click="deleteStore(store)"
              class="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
              title="刪除"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Add Modal Placeholder -->
    <div
      v-if="showAddModal"
      class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
      @click.self="showAddModal = false"
    >
      <div class="bg-white rounded-xl max-w-lg w-full p-6">
        <h2 class="text-xl font-bold text-gray-900 mb-4">新增門店</h2>
        <p class="text-gray-500 mb-6">此功能尚在開發中，請稍後再試。</p>
        <button
          @click="showAddModal = false"
          class="w-full bg-gray-100 text-gray-700 font-medium py-2.5 rounded-lg hover:bg-gray-200 transition-colors"
        >
          關閉
        </button>
      </div>
    </div>
  </div>
</template>
