// apps/newweb/pages/admin/stores/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'

definePageMeta({
  layout: 'admin'
})

useHead({
  title: '門店管理｜練健康後台',
})

interface Store {
  id: string
  name: string
  slug: string
  city?: string
  district?: string
  phone?: string
  sortOrder?: number
  isActive: boolean
  coachCount?: number
}

const stores = ref<Store[]>([])
const isLoading = ref(true)
const error = ref('')

async function fetchStores() {
  isLoading.value = true
  error.value = ''
  try {
    const response = await $fetch<{ success: boolean; data: Store[] }>('/api/admin/stores')
    if (response.success) {
      stores.value = response.data
    }
  } catch (e: any) {
    error.value = e.data?.message || '載入失敗'
    console.error('Error fetching stores:', e)
  } finally {
    isLoading.value = false
  }
}

async function toggleActive(store: Store) {
  try {
    await $fetch(`/api/admin/stores/${store.id}`, {
      method: 'PATCH',
      body: { isActive: !store.isActive },
    })
    store.isActive = !store.isActive
  } catch (e: any) {
    alert(e.data?.message || '更新失敗')
  }
}

async function deleteStore(store: Store) {
  if (!confirm(`確定要刪除「${store.name}」嗎？此操作無法復原。`)) return
  try {
    await $fetch(`/api/admin/stores/${store.id}`, {
      method: 'DELETE',
    })
    stores.value = stores.value.filter(s => s.id !== store.id)
  } catch (e: any) {
    alert(e.data?.message || '刪除失敗')
  }
}

onMounted(fetchStores)
</script>

<template>
  <div class="space-y-6">
    <!-- Page Header -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">門店管理</h1>
        <p class="text-gray-500 mt-1">管理所有門店資訊</p>
      </div>
      <NuxtLink
        to="/admin/stores/new"
        class="inline-flex items-center gap-2 bg-orange text-white font-medium px-4 py-2.5 rounded-lg hover:bg-orange-600 transition-colors"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
        </svg>
        新增門店
      </NuxtLink>
    </div>

    <!-- Error -->
    <div v-if="error" class="bg-red-50 text-red-600 px-4 py-3 rounded-lg">
      {{ error }}
    </div>

    <!-- Loading -->
    <div v-if="isLoading" class="flex items-center justify-center h-64">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-orange"></div>
    </div>

    <!-- Table -->
    <div v-else class="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">門店名稱</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">地區</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">電話</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">教練數</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">狀態</th>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">操作</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr v-if="stores.length === 0">
              <td colspan="6" class="px-6 py-12 text-center text-gray-500">
                目前沒有門店資料
              </td>
            </tr>
            <tr v-for="store in stores" :key="store.id" class="hover:bg-gray-50">
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="font-medium text-gray-900">{{ store.name }}</div>
                <div class="text-xs text-gray-400">{{ store.slug }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{ store.city }} {{ store.district }}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{ store.phone || '-' }}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{ store.coachCount ?? 0 }} 位
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <button
                  @click="toggleActive(store)"
                  :class="[
                    'text-xs font-medium px-2.5 py-1 rounded-full cursor-pointer transition-colors',
                    store.isActive ? 'bg-green-100 text-green-700 hover:bg-green-200' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                  ]"
                >
                  {{ store.isActive ? '上架中' : '已下架' }}
                </button>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">
                <div class="flex items-center gap-3">
                  <NuxtLink
                    :to="`/admin/stores/${store.id}`"
                    class="text-navy-700 hover:text-navy-800 font-medium"
                  >
                    編輯
                  </NuxtLink>
                  <button
                    @click="deleteStore(store)"
                    class="text-red-500 hover:text-red-600 font-medium"
                  >
                    刪除
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

// apps/web/app/admin/(dashboard)/stores/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

interface Store {
  id: string;
  slug: string;
  name: string;
  city: string;
  district: string;
  phone: string;
  coachCount: number;
  isActive: boolean;
}

export default function StoresPage() {
  const [stores, setStores] = useState<Store[]>([]);
  const [loading, setLoading] = useState(true);

  // 從 API 取得門店資料
  useEffect(() => {
    async function fetchStores() {
      try {
        const res = await fetch('/api/admin/stores');
        if (res.ok) {
          const data = await res.json();
          setStores(
            data.data.map((store: any) => ({
              id: store.id,
              slug: store.slug,
              name: store.name,
              city: store.city,
              district: store.district,
              phone: store.phone || '-',
              coachCount: store._count?.coaches || 0,
              isActive: store.isActive,
            }))
          );
        }
      } catch (error) {
        console.error('Failed to fetch stores:', error);
      } finally {
        setLoading(false);
      }
    }
    fetchStores();
  }, []);

  const handleToggleActive = async (storeId: string, currentStatus: boolean) => {
    try {
      const res = await fetch(`/api/admin/stores/${storeId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !currentStatus }),
      });
      if (res.ok) {
        setStores((prev) =>
          prev.map((s) => (s.id === storeId ? { ...s, isActive: !currentStatus } : s))
        );
      }
    } catch (error) {
      console.error('Toggle failed:', error);
    }
  };

  const handleDelete = async (storeId: string) => {
    if (confirm('確定要刪除此門店嗎？此操作無法復原。')) {
      try {
        const res = await fetch(`/api/admin/stores/${storeId}`, { method: 'DELETE' });
        if (res.ok) {
          setStores((prev) => prev.filter((s) => s.id !== storeId));
        } else {
          const data = await res.json();
          alert(data.error || '刪除失敗');
        }
      } catch (error) {
        console.error('Delete failed:', error);
      }
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-500">載入中...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold font-sans">門店管理</h1>
          <p className="text-gray-500 mt-1">管理所有門店資訊</p>
        </div>
        <Link href="/admin/stores/new" className="btn btn-primary flex items-center gap-2">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
          新增門店
        </Link>
      </div>

      {/* Table */}
      <div className="card border border-gray-200">
        <div className="table-container">
          <table className="table">
            <thead>
              <tr>
                <th>門店名稱</th>
                <th>地區</th>
                <th>電話</th>
                <th>教練數</th>
                <th>狀態</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {stores.length === 0 ? (
                <tr>
                  <td colSpan={6} className="text-center py-8 text-gray-500">
                    目前沒有門店資料
                  </td>
                </tr>
              ) : (
                stores.map((store) => (
                  <tr key={store.id}>
                    <td className="font-medium">{store.name}</td>
                    <td>
                      {store.city} {store.district}
                    </td>
                    <td>{store.phone}</td>
                    <td>{store.coachCount} 位</td>
                    <td>
                      <button
                        onClick={() => handleToggleActive(store.id, store.isActive)}
                        className={`badge cursor-pointer ${store.isActive ? 'badge-success' : 'badge-gray'}`}
                      >
                        {store.isActive ? '上架中' : '已下架'}
                      </button>
                    </td>
                    <td>
                      <div className="flex items-center gap-2">
                        <Link
                          href={`/admin/stores/${store.id}`}
                          className="text-navy-700 hover:text-navy-800 text-sm"
                        >
                          編輯
                        </Link>
                        <button
                          onClick={() => handleDelete(store.id)}
                          className="text-red-500 hover:text-red-600 text-sm"
                        >
                          刪除
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
